upload_max_filesize=40M
post_max_size=40M
memory_limit=256M
max_execution_time=120

; OPcache tuning for Docker performance
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.interned_strings_buffer=16
opcache.jit=1255
opcache.jit_buffer_size=128M
