sonar.projectKey=mfozmen_event-driven-notification
sonar.organization=mfozmen
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-results.xml
